name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install the gcloud CLI
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true

      - name: Build
        run: |
          echo 'Building ...'
          npm install
          echo 'Successfully built ...'

      - name: Test
        run: |
          echo 'Testing ...'
          # Add any testing commands here, such as `npm run test`

      - name: Build Docker Image & Push to the GCR
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          docker build -t asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/codimite-gcr/nodejs_app:latest .
          docker push asia-southeast1-docker.pkg.dev/${{ secrets.GOOGLE_PROJECT }}/codimite-gcr/nodejs_app:latest
